language: android
dist: trusty
android:
  components:
  - build-tools-26.0.2
  - android-26
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-x86-android-26
  - sys-img-armeabi-v7a-android-17
before_install:
- openssl aes-256-cbc -K $encrypted_17819ee4ac47_key -iv $encrypted_17819ee4ac47_iv
  -in google-services.json.enc -out ./app/google-services.json -d
